# Generated by Django 4.2 on 2023-04-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('idnum', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('housenum', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('payment', models.CharField(max_length=30)),
            ],
        ),
    ]
